import "./globals.css"
import { Poppins } from "next/font/google"
import { Providers } from "./providers"

const poppins = Poppins({ subsets: ["latin"], weight: "400" })

export const metadata = {
  title: "Portfolio | Tajul Subqi",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={poppins.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
